package com.sentinelbet.app.domain.entities

data class Team(
    val name: String,
    val league: String,
    val attackStrength: Double,
    val defenseStrength: Double,
)

val LEAGUES = listOf(
    "Brasileirão Série A",
    "Premier League",
    "La Liga",
    "Bundesliga",
    "Serie A",
    "Ligue 1",
    "Champions League",
    "Copa Libertadores",
)

private val TEAMS_DATA = mapOf(

    // ── Brasileirão Série A 2025 ──────────────────────────────────────────
    "Brasileirão Série A" to listOf(
        Team("Flamengo",          "Brasileirão Série A", 1.85, 0.95),
        Team("Palmeiras",         "Brasileirão Série A", 1.80, 0.85),
        Team("Botafogo",          "Brasileirão Série A", 1.70, 0.95),
        Team("Atlético Mineiro",  "Brasileirão Série A", 1.65, 1.00),
        Team("Fluminense",        "Brasileirão Série A", 1.50, 1.05),
        Team("São Paulo",         "Brasileirão Série A", 1.45, 1.05),
        Team("Internacional",     "Brasileirão Série A", 1.50, 1.00),
        Team("Corinthians",       "Brasileirão Série A", 1.35, 1.15),
        Team("Grêmio",            "Brasileirão Série A", 1.40, 1.10),
        Team("Athletico-PR",      "Brasileirão Série A", 1.45, 1.05),
        Team("Vasco da Gama",     "Brasileirão Série A", 1.30, 1.20),
        Team("Cruzeiro",          "Brasileirão Série A", 1.40, 1.10),
        Team("Bahia",             "Brasileirão Série A", 1.35, 1.15),
        Team("Fortaleza",         "Brasileirão Série A", 1.45, 1.05),
        Team("Bragantino",        "Brasileirão Série A", 1.40, 1.10),
        Team("Vitória",           "Brasileirão Série A", 1.20, 1.30),
        Team("Juventude",         "Brasileirão Série A", 1.15, 1.30),
        Team("Ceará",             "Brasileirão Série A", 1.25, 1.20),
        Team("Sport",             "Brasileirão Série A", 1.20, 1.25),
        Team("Mirassol",          "Brasileirão Série A", 1.20, 1.25),
    ),

    // ── Premier League 2024/25 ────────────────────────────────────────────
    "Premier League" to listOf(
        Team("Liverpool",         "Premier League", 2.10, 0.75),
        Team("Arsenal",           "Premier League", 1.90, 0.80),
        Team("Manchester City",   "Premier League", 2.00, 0.80),
        Team("Chelsea",           "Premier League", 1.70, 0.95),
        Team("Newcastle",         "Premier League", 1.55, 0.95),
        Team("Aston Villa",       "Premier League", 1.60, 1.00),
        Team("Tottenham",         "Premier League", 1.60, 1.10),
        Team("Manchester United", "Premier League", 1.40, 1.15),
        Team("West Ham",          "Premier League", 1.35, 1.15),
        Team("Brighton",          "Premier League", 1.50, 1.05),
        Team("Fulham",            "Premier League", 1.35, 1.10),
        Team("Brentford",         "Premier League", 1.40, 1.10),
        Team("Wolves",            "Premier League", 1.20, 1.20),
        Team("Everton",           "Premier League", 1.10, 1.20),
        Team("Crystal Palace",    "Premier League", 1.25, 1.15),
        Team("Nottm Forest",      "Premier League", 1.30, 1.05),
        Team("Bournemouth",       "Premier League", 1.35, 1.15),
        Team("Leicester City",    "Premier League", 1.20, 1.25),
        Team("Ipswich Town",      "Premier League", 1.10, 1.30),
        Team("Southampton",       "Premier League", 1.00, 1.40),
    ),

    // ── La Liga 2024/25 ───────────────────────────────────────────────────
    "La Liga" to listOf(
        Team("Real Madrid",       "La Liga", 2.20, 0.70),
        Team("Barcelona",         "La Liga", 2.10, 0.80),
        Team("Atlético Madrid",   "La Liga", 1.60, 0.75),
        Team("Athletic Club",     "La Liga", 1.50, 0.90),
        Team("Villarreal",        "La Liga", 1.50, 1.00),
        Team("Real Sociedad",     "La Liga", 1.45, 1.00),
        Team("Betis",             "La Liga", 1.40, 1.05),
        Team("Girona",            "La Liga", 1.50, 1.00),
        Team("Rayo Vallecano",    "La Liga", 1.20, 1.15),
        Team("Osasuna",           "La Liga", 1.20, 1.10),
        Team("Getafe",            "La Liga", 1.10, 1.05),
        Team("Sevilla",           "La Liga", 1.30, 1.10),
        Team("Celta Vigo",        "La Liga", 1.30, 1.15),
        Team("Valencia",          "La Liga", 1.20, 1.20),
        Team("Leganés",           "La Liga", 1.05, 1.25),
        Team("Espanyol",          "La Liga", 1.10, 1.25),
        Team("Mallorca",          "La Liga", 1.15, 1.10),
        Team("Las Palmas",        "La Liga", 1.20, 1.20),
        Team("Alavés",            "La Liga", 1.10, 1.25),
        Team("Valladolid",        "La Liga", 1.00, 1.35),
    ),

    // ── Bundesliga 2024/25 ────────────────────────────────────────────────
    "Bundesliga" to listOf(
        Team("Bayern München",    "Bundesliga", 2.40, 0.80),
        Team("Bayer Leverkusen",  "Bundesliga", 1.95, 0.85),
        Team("Borussia Dortmund", "Bundesliga", 1.85, 1.05),
        Team("RB Leipzig",        "Bundesliga", 1.75, 0.95),
        Team("Eintracht Frankfurt","Bundesliga", 1.60, 1.05),
        Team("Freiburg",          "Bundesliga", 1.40, 1.00),
        Team("Wolfsburg",         "Bundesliga", 1.35, 1.10),
        Team("Borussia M'gladbach","Bundesliga", 1.35, 1.15),
        Team("Werder Bremen",     "Bundesliga", 1.40, 1.10),
        Team("Hoffenheim",        "Bundesliga", 1.35, 1.15),
        Team("Stuttgart",         "Bundesliga", 1.60, 1.00),
        Team("Heidenheim",        "Bundesliga", 1.20, 1.20),
        Team("Mainz",             "Bundesliga", 1.25, 1.10),
        Team("Augsburg",          "Bundesliga", 1.20, 1.15),
        Team("Union Berlin",      "Bundesliga", 1.20, 1.20),
        Team("Bochum",            "Bundesliga", 1.10, 1.30),
        Team("Holstein Kiel",     "Bundesliga", 1.10, 1.30),
        Team("St. Pauli",         "Bundesliga", 1.15, 1.25),
    ),

    // ── Serie A 2024/25 ───────────────────────────────────────────────────
    "Serie A" to listOf(
        Team("Inter Milan",       "Serie A", 1.95, 0.75),
        Team("Napoli",            "Serie A", 1.85, 0.85),
        Team("Juventus",          "Serie A", 1.55, 0.85),
        Team("AC Milan",          "Serie A", 1.65, 0.95),
        Team("Atalanta",          "Serie A", 1.80, 0.90),
        Team("Lazio",             "Serie A", 1.55, 1.00),
        Team("Fiorentina",        "Serie A", 1.50, 1.00),
        Team("Roma",              "Serie A", 1.50, 1.05),
        Team("Torino",            "Serie A", 1.30, 1.05),
        Team("Bologna",           "Serie A", 1.40, 1.05),
        Team("Udinese",           "Serie A", 1.20, 1.15),
        Team("Genoa",             "Serie A", 1.20, 1.20),
        Team("Parma",             "Serie A", 1.20, 1.20),
        Team("Cagliari",          "Serie A", 1.15, 1.20),
        Team("Lecce",             "Serie A", 1.10, 1.25),
        Team("Hellas Verona",     "Serie A", 1.20, 1.25),
        Team("Empoli",            "Serie A", 1.15, 1.15),
        Team("Como",              "Serie A", 1.20, 1.20),
        Team("Venezia",           "Serie A", 1.10, 1.30),
        Team("Monza",             "Serie A", 1.15, 1.20),
    ),

    // ── Ligue 1 2024/25 ───────────────────────────────────────────────────
    "Ligue 1" to listOf(
        Team("Paris Saint-Germain","Ligue 1", 2.30, 0.75),
        Team("Monaco",            "Ligue 1", 1.80, 0.90),
        Team("Marseille",         "Ligue 1", 1.65, 1.00),
        Team("Lyon",              "Ligue 1", 1.55, 1.05),
        Team("Lille",             "Ligue 1", 1.55, 0.95),
        Team("Nice",              "Ligue 1", 1.45, 1.00),
        Team("Lens",              "Ligue 1", 1.40, 1.05),
        Team("Rennes",            "Ligue 1", 1.40, 1.05),
        Team("Strasbourg",        "Ligue 1", 1.30, 1.15),
        Team("Montpellier",       "Ligue 1", 1.20, 1.20),
        Team("Toulouse",          "Ligue 1", 1.25, 1.15),
        Team("Nantes",            "Ligue 1", 1.20, 1.20),
        Team("Brest",             "Ligue 1", 1.45, 1.00),
        Team("Reims",             "Ligue 1", 1.20, 1.15),
        Team("Le Havre",          "Ligue 1", 1.10, 1.25),
        Team("Auxerre",           "Ligue 1", 1.15, 1.20),
        Team("Angers",            "Ligue 1", 1.10, 1.25),
        Team("Saint-Étienne",     "Ligue 1", 1.10, 1.30),
    ),

    // ── Champions League (Fase de Grupos 2024/25 — principais clubes) ─────
    "Champions League" to listOf(
        Team("Real Madrid",       "Champions League", 2.25, 0.70),
        Team("Manchester City",   "Champions League", 2.10, 0.75),
        Team("Bayern München",    "Champions League", 2.20, 0.80),
        Team("Paris Saint-Germain","Champions League",2.10, 0.85),
        Team("Barcelona",         "Champions League", 2.00, 0.80),
        Team("Liverpool",         "Champions League", 2.05, 0.75),
        Team("Inter Milan",       "Champions League", 1.90, 0.80),
        Team("Arsenal",           "Champions League", 1.85, 0.80),
        Team("Atlético Madrid",   "Champions League", 1.65, 0.75),
        Team("Bayer Leverkusen",  "Champions League", 1.85, 0.90),
        Team("Borussia Dortmund", "Champions League", 1.80, 1.00),
        Team("Juventus",          "Champions League", 1.55, 0.90),
        Team("AC Milan",          "Champions League", 1.60, 0.95),
        Team("Benfica",           "Champions League", 1.70, 0.95),
        Team("Porto",             "Champions League", 1.60, 1.00),
        Team("Celtic",            "Champions League", 1.45, 1.10),
    ),

    // ── Copa Libertadores 2025 (principais clubes) ────────────────────────
    "Copa Libertadores" to listOf(
        Team("Flamengo",          "Copa Libertadores", 1.90, 0.90),
        Team("Palmeiras",         "Copa Libertadores", 1.85, 0.85),
        Team("Botafogo",          "Copa Libertadores", 1.70, 0.95),
        Team("Atlético Mineiro",  "Copa Libertadores", 1.65, 1.00),
        Team("Fluminense",        "Copa Libertadores", 1.55, 1.00),
        Team("Internacional",     "Copa Libertadores", 1.50, 1.00),
        Team("River Plate",       "Copa Libertadores", 1.85, 0.85),
        Team("Boca Juniors",      "Copa Libertadores", 1.70, 0.95),
        Team("Racing Club",       "Copa Libertadores", 1.65, 0.95),
        Team("Vélez Sársfield",   "Copa Libertadores", 1.45, 1.05),
        Team("Nacional (URU)",    "Copa Libertadores", 1.50, 1.00),
        Team("Peñarol",           "Copa Libertadores", 1.55, 1.00),
        Team("LDU Quito",         "Copa Libertadores", 1.40, 1.05),
        Team("Colo-Colo",         "Copa Libertadores", 1.45, 1.05),
        Team("Universitario",     "Copa Libertadores", 1.35, 1.10),
        Team("Bolívar",           "Copa Libertadores", 1.35, 1.10),
    ),
)

fun getTeamsForLeague(league: String): List<Team> = TEAMS_DATA[league] ?: emptyList()
